### PR TITLE
cifxyz

### PR DESCRIPTION
**Pull request by Jo-stfc**
allow cif and xyz formats for structures (using *.cif, *.cell and *.xyz as selectors)

### CODE REVIEW

**Review by elichad — COMMENTED** [review]
These changes look good to me, but currently semi-blocked by https://github.com/muon-spectroscopy-computational-project/pymuon-suite/issues/50

**Comment by Jo-stfc** [comment]
I've added the random_seed param on the yaml tool generator and tested it as well, diff between the generated structures only varied on chden_path, which included the job container id in the absolute path

**Comment by elichad** [comment]
Linting fails because of https://github.com/galaxyproject/planemo/issues/1229
Expected test failures are temporary due to https://github.com/muon-spectroscopy-computational-project/pymuon-suite/issues/50

**Review by anish-mudaraddi — APPROVED** [review]
Changes look good.
I'm guessing we should hold off on merging until the expected test failures are fixed?

**Comment by elichad** [comment]
As it's just linting that's broken I don't mind leaving it, on a temporary basis (ether planemo gets fixed or we resolve the problem in pymuon-suite) – as long as we check failed CI workflows carefully to make sure nothing else is failing too. 
Alternatively, I can rewrite or remove the failing tests, but we may have to remember to re-enable them later.
Which option do you prefer?

**Comment by elichad** [comment]
As it's just linting that's broken I don't mind leaving it, on a temporary basis (ether planemo gets fixed or we resolve the problem in pymuon-suite) – as long as we check failed CI workflows carefully to make sure nothing else is failing too. 
Alternatively, I can rewrite or remove the failing tests, but we may have to remember to re-enable them later.
Which option do you prefer?

**Comment by anish-mudaraddi** [comment]
> Which option do you prefer?
Happy with merging it as is.

**Comment by elichad** [comment]
Yep, go ahead

**Pull request merged**
